import { catalog } from "../src/commands/index.js";
import type { Manifest } from "../src/spec/types.js";

export const BEGIN_MARKER = "<!-- BEGIN COMMAND REFERENCE -->";
export const END_MARKER = "<!-- END COMMAND REFERENCE -->";

function cell(s: string): string {
  return s.replace(/\s+/g, " ").replace(/\|/g, "\\|").trim();
}

/** The README command reference: hand-written commands, then one table per API group. */
export function renderReference(manifest: Manifest): string {
  const lines: string[] = [
    BEGIN_MARKER,
    "<!-- Generated by scripts/generate.ts from spec/openapi.json. Do not edit by hand. -->",
    "",
    `${manifest.operationCount} API operations in ${manifest.groups.length} groups, plus the hand-written commands below.`,
    "",
    "#### Hand-written commands",
    "",
    "| Command | What it does |",
    "| --- | --- |",
  ];
  const hand = [...catalog.top.filter((t) => !t.hidden), ...catalog.extensions];
  for (const cmd of hand) {
    const path = cmd.group ? `${cmd.group} ${cmd.name}` : cmd.name;
    const args = (cmd.args ?? []).map((a) => (a.optional ? ` [${a.name}]` : ` <${a.name}>`)).join("");
    lines.push(`| \`${cell(`smtpfast ${path}${args}`)}\` | ${cell(cmd.summary)} |`);
  }
  for (const group of manifest.groups) {
    const replacements = new Map(catalog.extensions.filter((e) => e.group === group.name && e.replaces).map((e) => [e.replaces!, e]));
    lines.push("", `#### ${group.name}`, "", cell(group.description), "", "| Command | API | What it does |", "| --- | --- | --- |");
    for (const op of manifest.operations.filter((o) => o.group === group.name)) {
      const ext = replacements.get(op.operationId);
      const args = ext
        ? (ext.args ?? []).map((a) => ` <${a.name}>`).join("")
        : op.pathParams.map((p) => ` <${p.name}>`).join("");
      const summary = ext ? `${ext.summary} (hand-written)` : op.summary;
      lines.push(`| \`${cell(`smtpfast ${op.group} ${op.command}${args}`)}\` | \`${op.method} ${op.path}\` | ${cell(summary)} |`);
    }
  }
  lines.push(END_MARKER);
  return lines.join("\n");
}

/** Replace the text between the markers. Throws when the markers are missing. */
export function updateReadme(readme: string, manifest: Manifest): string {
  const start = readme.indexOf(BEGIN_MARKER);
  const end = readme.indexOf(END_MARKER);
  if (start === -1 || end === -1 || end < start) throw new Error(`README.md needs ${BEGIN_MARKER} and ${END_MARKER} markers`);
  return `${readme.slice(0, start)}${renderReference(manifest)}${readme.slice(end + END_MARKER.length)}`;
}
